### ISSUE TITLE
Migrate to albacore v2.x

### ISSUE THREAD

**Issue by chester89** [FluentNHibernate/fluent-nhibernate#293]
The build script now uses albacore 1.0.0.rc2, I'd like to update it to 2.0. May be [this](https://github.com/schambers/fluentmigrator/pull/565) can help. My initial attempt to do this failed, now there are more documentation on v2 and OSS projects that use it

**Comment by scardetto** [comment]
I'd be happy to take this on. Also I noticed that the rake tasks don't depend on each other. For example to run tests, you typically want to set the compile step as a dependency. Is this something you'd be interested in setting up?

**Comment by chester89** [comment]
​Yep, I definitely need to do that.​

2015-02-10 16:46 GMT+03:00 Rob Scaduto <notifications@github.com>:

> I'd be happy to take this on. Also I noticed that the rake tasks don't
> depend on each other. For example to run tests, you typically want to set
> the compile step as a dependency. Is this something you'd be interested in
> setting up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/293#issuecomment-73700993>
> .
>



-- 
С уважением,
Чермённов Глеб

**Comment by scardetto** [comment]
No worries, I'll set it up and you can review.

**Comment by chester89** [comment]
Any news on that @scardetto?

**Comment by scardetto** [comment]
Sorry for the delay.  I have been crazy busy.

I have made some good progress, but hit a speedbump an issue with the zip library provided by the new version of Albacore.  The last issue I need to address is that it's currently not filtering out the requested files for the source zip.

Other than that, everything is in pretty good shape.  I should have something to look at early next week.

**Comment by chester89** [comment]
Awesome. There's no hurry, just checking in

2015-06-05 1:27 GMT+03:00 Rob Scaduto <notifications@github.com>:

> Sorry for the delay. I have been crazy busy.
>
> I have made some good progress, but hit a speedbump an issue with the zip
> library provided by the new version of Albacore. The last issue I need to
> address is that it's currently not filtering out the requested files for
> the source zip.
>
> Other than that, everything is in pretty good shape. I should have
> something to look at early next week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/293#issuecomment-109072557>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by jrgcubano** [comment]
We change to Cake!
