### ISSUE TITLE
Fluent-NHibernate does not work with the current NHibernate (5.0)

### ISSUE THREAD

**Issue by MKiCD** [FluentNHibernate/fluent-nhibernate#383]
NHibernate 5.0 is released since October 2017! Certainly with great improvements.
I asked one of the developers here about the risk to use NH 5 with Fluent and he found out, that the current fluent-nhibernate does not compile in this combination.
Initially I was surprised that the fluent nuget added NH 4 to my project, where NH5 was already present.
I think some people besides me would be happy to see this winning combination (FL-NH-5)!

**Comment by naiii** [comment]
Any news on this? in #365 was said that an update was on the way, what's the status on that?

**Comment by jrgcubano** [comment]
Implemented on #385

**Comment by MKiCD** [comment]
@jrgcubano Great that yoou took that task. Thank you! 
Lets me think again to return to NHibernate.

**Comment by EnemyArea** [comment]
Holy s*** Thank you so much :D

**Comment by ivanmartinvalle** [comment]
I'm on NHibernate 5.0.3 and FluentNHibernate 1.4.0 with the following binding redirect and am able to load the application without any problems.

```
<dependentAssembly>
    <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-5.0.3.0" newVersion="5.0.0.0" />
</dependentAssembly>
```

Granted, I do have some many-to-mapping mapping issues, but I think that's either on me or NHibernate.
