### ISSUE TITLE
Update to NHibernate 5+ and net framework

### ISSUE THREAD

**Issue by jrgcubano** [FluentNHibernate/fluent-nhibernate#385]

**Comment by TiltonJH** [comment]
Please make a NuGet release (or a prerelease) for that new version.

thx

**Comment by jrgcubano** [comment]
FluentNHibernate is back 

Finally we shipped the new versio:

https://www.nuget.org/packages/FluentNHibernate/2.1.0

Sorry for the delay!

**Comment by gudmundurm** [comment]
@jrgcubano  Fantastic news!!! Well done :-)
