### ISSUE TITLE
Support NETStandard 2.0 and NETCore 2.0

### ISSUE THREAD

**Issue by jedielson** [FluentNHibernate/fluent-nhibernate#390]
Hi.

Whit the release of version [5.1.0](https://www.nuget.org/packages/NHibernate/) of nhibernate, when this one will support net standard 2.0 too?

**Comment by vincentparrett** [comment]
I just submitted PR #391 for this. NHibernate and FluentNHibernate were the 2 projects holding me back from migrating to netstandard 2.0.

**Comment by vgelmut** [comment]
I'm really waiting for this one. NHibernate released, but nobody using it without this awesome Fluent library

**Comment by gudmundurm** [comment]
@jrgcubano Can you help ?

**Comment by mgoodfellow** [comment]
While I'm waiting for a new package to be issued, I'm happily using the changes from @vincentparrett's PR https://github.com/FluentNHibernate/fluent-nhibernate/pull/391 - Thanks for those! I'm just using local packages for now, but I guess one could temporarily issue a nuget package from a fork such as https://github.com/FluentNHibernate/fluent-nhibernate/pull/391 to allow other users to continue with netstandard support. I have seen similar things done before while waiting for the main repo contributors to approve official changes (such as here https://www.nuget.org/packages/HangFire.SimpleInjector.Core, while waiting on https://www.nuget.org/packages/Hangfire.SimpleInjector/)

**Comment by danilobreda** [comment]
@mgoodfellow ok i will try to made it.

**Comment by jrgcubano** [comment]
@vincentparrett @danilobreda Sorry for the delay in answering ... Tomorrow I will try to review it.

Thank you!

**Comment by giggio** [comment]
Awesome, NH and FluentNH on .NET Std change everything.

**Comment by neseih** [comment]
Just found out that dotnetcore compatibility needs a new DeepClone function for ClassMaps. The existing one uses serialize/deserialize that don't work on System.RuntimeType on dotnet core.

**Comment by reinaldocoelho** [comment]
I think it´s solved on DotNet Core 2.1, based on issue below:
https://github.com/dotnet/corefx/issues/23213

**Comment by neseih** [comment]
I can't see any hint in this issue (dotnet/corefx#23213) if this will be solved in 2.1 or later. They talk about a workaround (serialize System.RuntimeType to class name) and that must be changed in fluent nhibernate codebase.

For completeness, the stack trace (on 2.0):

`at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at FluentNHibernate.Utils.Extensions.DeepClone[T](T obj)
   at FluentNHibernate.Visitors.SeparateSubclassVisitor.ProcessClass(ClassMapping mapping)
   at FluentNHibernate.MappingModel.ClassBased.ClassMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.MappingModel.HibernateMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.Utils.CollectionExtensions.Each[T](IEnumerable1 enumerable, Action1 each)
   at FluentNHibernate.PersistenceModel.ApplyVisitors(IEnumerable1 mappings)
   at FluentNHibernate.PersistenceModel.BuildMappings()
   at FluentNHibernate.PersistenceModel.EnsureMappingsBuilt()
   at FluentNHibernate.PersistenceModel.Configure(Configuration cfg)
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration()`

**Comment by jrgcubano** [comment]
I had not noticed this. Any idea to fix it without breaking changes @neseih @reinaldocoelho?

**Comment by vincentparrett** [comment]
The problem is th DeepClone using binary serialization. That method is only called from 2 places, it should be possible to do the cloning manually (implement a clone method on the classes involved).

**Comment by reinaldocoelho** [comment]
I think the @vincentparrett solution is the best, considering the performance issue.
Other way would be choose another serialization option instead.

**Comment by danilobreda** [comment]
I use this solution on my projects, maybe it can help. [DeepCloner Github](https://github.com/force-net/DeepCloner )

**Comment by vincentparrett** [comment]
@danilobreda I think it would be silly to take a another dependency for what looks a simple problem. In my quick reading of the code where DeepClone<T> is used, there are only a few classes where a clone method needs to be added, most of the methods involved already new up a an instance to return. AttributeStore already has a clone method.  I'm not familiar enough with the code to know what exactly needs to be added, or indeed why the cloning is needed?

**Comment by neseih** [comment]
I don't event understand, why cloning is needed as these classes (ClassMaps) are only descriptive. But I'm not familiar enough with the internals.

**Comment by rcollina** [comment]
Hello everyone, is there a prelease nuget package published anywhere? 
Or an ETA for the official package?

We're currently evaluating NHibernate but without Fluent is a non-starter. 

Thank you!

**Comment by jrgcubano** [comment]
I'm working on it guys, but there were more problems than expected. I'll try to finish it tomorrow.

**Comment by hikeeba** [comment]
Appreciate all your effort @jrgcubano. This is a great package and I can't wait for .netcore.

**Comment by giggio** [comment]
@rcollina Looking at the build logs I can see that the latest `master` build did not push the Nuget artificats anywhere. It would be nice to publish these intermediate nupkgs to Myget, but it doesn't look like it is being done.
BUT! The nupkg is being saved on the build artifacts from AppVeyor. You can download it there and add it to some local Nuget feed.
This is the latest one:
https://ci.appveyor.com/project/jrogalan/fluent-nhibernate/build/2.1.1+2.build.8/artifacts
I have not tested it yet, but the build passed, so it should be working. I looked into the nupkg, and it does target netstd2.
If this is working it would be nice if the maintainers would push a `2.1.1-alpha1` to Nuget.

**Comment by giggio** [comment]
Ok, I just tested it and that nupkg is working just fine on a simple project.

**Comment by giggio** [comment]
Ok, I created a non official feed and uploaded the nupkg from the above build there with the also unoficial version `2.1.1-alpha1`. If you want to try it the feed source is:
https://www.myget.org/F/fluentnh-nonofficial/api/v3/index.json
To the maintainers: as soon as you create a pre-release feed I will erase this one. This is just so we can test it by now.

**Comment by Zaixer** [comment]
I get an exception "System.Runtime.Serialization.SerializationException" when running that package, but that is not in a simple project.

**Comment by jrgcubano** [comment]
Sorry for the delay guys. I was pretty busy.

**Comment by giggio** [comment]
@jrgcubano Thank YOU! Feed deleted. I am already updating my projects. Thanks a LOT! That one of the last missing pieces for me to move away from EF. FluentMigrator also updated today.

**Comment by neseih** [comment]
@jrgcubano Thanks a lot. This was the last missing piece for the dotnet core migration!

**Comment by jedielson** [comment]
Thanks a lot guys!!!

**Comment by aferia** [comment]
Thanks for this!

**Comment by shatl** [comment]
Awesome! Thanks a lot

**Comment by jrgcubano** [comment]
@giggio It would be awesome if you got some time and do a PR with some example in netcore or correct the current ones.
