### ISSUE TITLE
Incorrect dll version(1.1.0 instead of 2.1.0)

### ISSUE THREAD

**Issue by aliluyko89** [FluentNHibernate/fluent-nhibernate#392]
After installation of package using nuget and running following command **Install-Package FluentNHibernate -Version 2.1.0**
I noticed that installed lib has version 1.1.0 instead of 2.1.0
I marked all lib versions on screen
![image](https://user-images.githubusercontent.com/16755495/37705880-14ea11d2-2d06-11e8-8cfd-d6372475b79c.png)

**Comment by michalkowal** [comment]
Pull Request ready for review: #396
