### ISSUE TITLE
Refactor MsSqlConnectionStringBuilder to remove System.Data.SqlClient dependency

### ISSUE THREAD

**Issue by jrgcubano** [FluentNHibernate/fluent-nhibernate#393]
We need to change [MsSqlConnectionStringBuilder ](https://github.com/FluentNHibernate/fluent-nhibernate/blob/master/src/FluentNHibernate/Cfg/Db/MsSqlConnectionStringBuilder.cs ) "ToString" implementation so we can remove the need for System.Data.SqlClient.SqlConnectionStringBuilder and System.Data.SqlClient package.

Basic refactor idea:

Follow the same implementation as [MySQLConnectionStringBuilder](https://github.com/FluentNHibernate/fluent-nhibernate/blob/master/src/FluentNHibernate/Cfg/Db/MySQLConnectionStringBuilder.cs).

**Comment by danilobreda** [comment]
I will submit a PR for this.

**Comment by danilobreda** [comment]
@jrgcubano the PR is **done**, i am open for revision.
I think this is very important to target the 2.1.1 milestone.

I did not remove the package dependency yet (i don't know how to do it on the right way).
