### ISSUE TITLE
Package frameworks dependencies

### ISSUE THREAD

**Issue by i4004** [FluentNHibernate/fluent-nhibernate#411]
The latest (i didn't check previous) package is not showing frameworks dependencies (in package manager and nuget web-site also):

![default](https://user-images.githubusercontent.com/5744532/39258219-48495a0c-48d5-11e8-9d3a-6d68f3854ff1.png)

I tried to build for testing purposes using "GeneratePackageOnBuild" setting, and it is looks like:

![default](https://user-images.githubusercontent.com/5744532/39258360-a8703e28-48d5-11e8-935e-ac72e506b2d7.png)

Is this correct what frameworks dependencies is missing in release package?

**Comment by jrgcubano** [comment]
Hi @i4004 

I'm not an expert on nuget, but I do not think it's a big problem. We could do a PR with those small changes if you like?. What do you think?

Something like
```
...
    <dependencies>
      <group targetFramework="net461" />
      <group targetFramework="netstandard2.0">
        <dependency id="NHibernate" version="5.1.1" />
      </group>
      <group targetFramework="netcoreapp2.0">
        <dependency id="NHibernate" version="5.1.1" />
      </group>
    </dependencies>
...
```

**Comment by i4004** [comment]
I think that's ok! I created a pull request for that :)
