### ISSUE TITLE
Does fluent nhibernate support NHibernate 5.3.0 ?

### ISSUE THREAD

**Issue by namer315** [FluentNHibernate/fluent-nhibernate#457]
Hi

I have a project using NHibernate 5.2.7, everything works fine with the fluent Nhibernate.
after upgrading to NHibernate 5.3.0, the mapping stopped working.

Kindly see the error message occurs per mapping below:

"Could not load file or assembly 'NHibernate, Version=5.1.0.0, Culture=neutral, PublicKeyToken=aa95f207798dfdb4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
 
Does fluent nhibernate support NHibernate 5.3.0 ?

Thanks in advance

**Comment by satishviswanathan** [comment]
Yes it's breaking for me too.

**Comment by namer315** [comment]
the issue was sorted out by upgrading the .Net framework to 4.7.2
then NHibernate 5.3.0 worked with Fluent Nhibernate

**Comment by igitur** [comment]
> the issue was sorted out by upgrading the .Net framework to 4.7.2
> then NHibernate 5.3.0 worked with Fluent Nhibernate

So maybe close the issue then?

**Comment by namer315** [comment]
the issue was sorted out by upgrading the .Net framework to 4.7.2
then NHibernate 5.3.0 worked with Fluent Nhibernate
